plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'ru.otus.App'
}

group = 'ru.otus.java.proffesional'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes 'Main-Class': 'ru.otus.App'
    }

    // стратегия обработки дубликатов
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    // добавить все зависимости внутрь JAR
    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}